name: Release

on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@testing
        with:
          args: 'dist/bin/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

