on:
  push:
    tags: '*'
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag-data
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@testing
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          update_existing: true
          release_text: ${{ steps.tag-data.outputs.git-tag-annotation }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

